language: go

env:
  - DOCKER_HUB_REPO: "dtr0x80/rapt0r"

services:
  - docker

before_install:
  - docker build --no-cache -t ${DOCKER_HUB_REPO}:latest .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${DOCKER_HUB_REPO}:latest
